import fs from 'node:fs'; import vm from 'node:vm'; import assert from 'node:assert/strict';
const c={Zotero:{getMainWindow:()=>null,Attachments:{importFromFile:async x=>x},debug:()=>{}},PathUtils:{join:(...p)=>p.join('/')},IOUtils:{makeDirectory:async()=>{},read:async()=>new Uint8Array([37,80,68,70,45]),exists:async()=>false},Services:{prompt:{confirm:()=>false}}};
vm.createContext(c); vm.runInContext(fs.readFileSync('skill-fulltext-downloader.js','utf8')+';this.p=SkillFulltextDownloader',c); const p=c.p;
let calls=[]; p._scanSciCommand=async a=>calls.push(a);p._pickAttachmentFile=async()=>'/work/scansci/paper.pdf';p._findExistingPDFAttachment=async()=>null;
const item={id:9,getField:()=>''};let a=await p._tryScanSci(item,'10.1/a','/work');assert.equal(a.parentItemID,9);assert.equal(calls[0][0],'get');assert.ok(calls[0].includes('legal_only'));
p._pickAttachmentFile=async()=>null; assert.equal(await p._tryScanSci(item,'q','/work'),null);
p.cancelled=true; let n=calls.length;assert.equal(await p._tryScanSci(item,'q','/work'),null);assert.equal(calls.length,n);
console.log('PASS ScanSci PDF import, explicit strategy, missing PDF, cancellation');
p.cancelled=false; c.IOUtils.exists=async()=>true;c.IOUtils.readUTF8=async()=> 'login_required';c.Services.prompt.confirm=()=>true;
let picks=0;p._pickAttachmentFile=async()=>++picks===1?null:'/w/a.pdf';calls=[];
await p._tryScanSci({id:9,getField:f=>f==='DOI'?'10.1/a':''},'10.1/a','/w');assert.equal(calls.length,3);assert.equal(calls[1][0],'login');
p._scanSciSessionDir=()=>'/private-session';let removed;c.IOUtils.remove=async path=>removed=path;p.isRunning=false;p.activeProcess=null;await p._clearScanSciSession();assert.equal(removed,'/private-session');
console.log('PASS login consent -> login -> retry; clear is scoped to private session');
